### ISSUE TITLE
Not able to run test cases - error in ....`load_appium_txt': toml doesn't exist...

### ISSUE THREAD

**Issue by vikramvi** [carolmirakove/appium-native-rspec-example#2]
Hi carolmirakove,

I tried running catalog_spec.rb and got below errors

/Users/vikramingleshwar/.rvm/rubies/ruby-2.1.1/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/bin/rspec /Users/vikramingleshwar/Documents/workspace/iOS/appium-native-rspec-example/ios/spec/catalog_spec.rb --require teamcity/spec/runner/formatter/teamcity/formatter --format Spec::Runner::Formatter::TeamcityFormatter
Testing started at 11:23 ...
/Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/gems/appium_lib-4.1.0/lib/appium_lib/driver.rb:87:in `load_appium_txt': toml doesn't exist /Users/vikramingleshwar/Documents/workspace/iOS/appium-native-rspec-example/appium.txt (RuntimeError)
    from /Users/vikramingleshwar/Documents/workspace/iOS/appium-native-rspec-example/ios/spec/helper_spec.rb:6:in`<top (required)>'
    from /Users/vikramingleshwar/Documents/workspace/iOS/appium-native-rspec-example/ios/spec/catalog_spec.rb:1:in `require_relative'
    from /Users/vikramingleshwar/Documents/workspace/iOS/appium-native-rspec-example/ios/spec/catalog_spec.rb:1:in`<top (required)>'
    from /Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `load'
    from /Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in`block in load_spec_files'
    from /Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `each'
    from /Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in`load_spec_files'
    from /Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:97:in `setup'
    from /Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:85:in`run'
    from /Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:70:in `run'
    from /Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:38:in`invoke'
    from /Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.0.3/exe/rspec:4:in `<top (required)>'
    from /Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/bin/rspec:23:in`load'
    from /Users/vikramingleshwar/.rvm/gems/ruby-2.1.1/bin/rspec:23:in `<top (required)>'
    from -e:1:in`load'
    from -e:1:in `<main>'

Process finished with exit code 1
Empty test suite.

---

Please let me know what am I doing wrong here.

Also do you have sample android + ruby project , which I can try out along with this iOS project.

Thanks in advance.

Best Regards,
Vikram

**Comment by reach2jeyan** [comment]
@vikramvi Any solutions to this?

**Comment by gunesmes** [comment]
Updating the `tomlrb` fixed it for me:

`gem install tomlrb`
